# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
