# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumyapp', '0002_auto_20170905_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cod_valid',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
